# Generated by Django 5.0.1 on 2024-01-31 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
