# Generated by Django 5.0.1 on 2024-01-31 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
